EVENT_WEBHOOK_CALLBACK_VERIFICATION = 'webhook_callback_verification'
EVENT_NOTIFICATION = 'notification'

CTX_TOKEN_KEY = 'token'
CTX_USER_KEY = 'user'

SUBSCRIPTION_TYPE_CHANNEL_FOLLOW = 'channel.follow'
SUBSCRIPTION_TYPE_STREAM_ONLINE = 'stream.online'
SUBSCRIPTION_TYPE_STREAM_OFFLINE = 'stream.offline'

SUBSCRIPTION_TYPES = (
    SUBSCRIPTION_TYPE_CHANNEL_FOLLOW,
    SUBSCRIPTION_TYPE_STREAM_ONLINE,
    SUBSCRIPTION_TYPE_CHANNEL_FOLLOW
)
